use ifoodSamuel;

-- Tabela: FORMA_DE_PAGAMENTO
CREATE TABLE FORMA_DE_PAGAMENTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TIPO_DE_PAGAMENTO VARCHAR(50) NOT NULL
);

-- Tabela: STATUS_ENTREGA
CREATE TABLE STATUS_ENTREGA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL
);

-- Tabela: CATEGORIA
CREATE TABLE CATEGORIA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TIPO VARCHAR(50) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO TEXT
);

-- Tabela: ENDERECO
CREATE TABLE ENDERECO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    RUA VARCHAR(255) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    COMPLEMENTO VARCHAR(255),
    BAIRRO VARCHAR(255) NOT NULL,
    CIDADE VARCHAR(255) NOT NULL,
    ESTADO VARCHAR(2) NOT NULL,
    CEP VARCHAR(10) NOT NULL,
    IVA DECIMAL(5, 2)
);

-- Tabela: RESTAURANTE
CREATE TABLE RESTAURANTE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    ENDERECO TEXT,
    TELEFONE VARCHAR(20),
    CATEGORIA_ID INT,
    HORA_FUNCIO TIME,
    IS_RETIRADA BOOLEAN,
    FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA(ID)
);

-- Tabela: PROMO
CREATE TABLE PROMO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    VALOR DECIMAL(10, 2),
    CODIGO VARCHAR(50),
    VALIDADO BOOLEAN
);

-- Tabela: PRODUTO
CREATE TABLE PRODUTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO TEXT,
    PRECO DECIMAL(10, 2) NOT NULL,
    ID_CATEGORIA INT,
    ID_RESTAURANTE INT,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID),
    FOREIGN KEY (ID_RESTAURANTE) REFERENCES RESTAURANTE(ID)
);

-- Tabela: ACOMPANHAMENTO
CREATE TABLE ACOMPANHAMENTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO TEXT,
    VALOR DECIMAL(10, 2)
);

-- Tabela: PEDIDO
CREATE TABLE PEDIDO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DATA DATETIME NOT NULL,
    ID_RESTAURANTE INT NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    TAXA_ENTREGA DECIMAL(10, 2) NOT NULL,
    ID_PROMO INT,
    ID_STATUS_ENTREGA INT NOT NULL,
    ID_FORMA_PAGAMENTO INT,
    OBS TEXT,
    TROCO DECIMAL(10, 2),
    ID_ENDERECO INT NOT NULL,
    FOREIGN KEY (ID_RESTAURANTE) REFERENCES RESTAURANTE(ID),
    FOREIGN KEY (ID_PROMO) REFERENCES PROMO(ID),
    FOREIGN KEY (ID_STATUS_ENTREGA) REFERENCES STATUS_ENTREGA(ID),
    FOREIGN KEY (ID_FORMA_PAGAMENTO) REFERENCES FORMA_DE_PAGAMENTO(ID),
    FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID)
);

-- Tabela: PEDIDO_PRODUTO
CREATE TABLE PEDIDO_PRODUTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_PEDIDO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID)
);

-- Tabela: PEDIDO_PRODUTO_ACOMP
CREATE TABLE PEDIDO_PRODUTO_ACOMP (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_PEDIDO_PRODUTO INT NOT NULL,
    ID_ACOMP INT NOT NULL,
    FOREIGN KEY (ID_PEDIDO_PRODUTO) REFERENCES PEDIDO_PRODUTO(ID),
    FOREIGN KEY (ID_ACOMP) REFERENCES ACOMPANHAMENTO(ID)
);

-- Tabela: HISTORICO_PAGAMENTO
CREATE TABLE HISTORICO_PAGAMENTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DATA DATETIME NOT NULL,
    ID_FORMA_PAGAMENTO INT NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ID_FORMA_PAGAMENTO) REFERENCES FORMA_DE_PAGAMENTO(ID)
);

-- Tabela: HISTORICO_ENTREGA
CREATE TABLE HISTORICO_ENTREGA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_STATUS_ENTREGA INT NOT NULL,
    ID_PEDIDO INT NOT NULL,
    DATA DATETIME NOT NULL,
    FOREIGN KEY (ID_STATUS_ENTREGA) REFERENCES STATUS_ENTREGA(ID),
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID)
);

-- Tabela: AVALIACAO
CREATE TABLE AVALIACAO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOTA INT NOT NULL,
    ID_PEDIDO INT NOT NULL,
    RETORNO TEXT,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID)
);
